// Generated by eve. Do not edit by hand.
import { POST } from "../../../node_modules/eve/.eve/workflow-cache/61a38eeae793/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
