// Generated by eve. Do not edit by hand.
import { POST } from "../../../node_modules/eve/.eve/workflow-cache/8ed9478c9ab3/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
