// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/tools/generate-email.ts";
import * as module_3 from "../../agent/tools/save-draft.ts";
import * as module_4 from "../../agent/tools/search-leads.ts";
import * as module_5 from "../../agent/tools/search-prospeo.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/generate-email.ts": module_2,
                  "tools/save-draft.ts": module_3,
                  "tools/search-leads.ts": module_4,
                  "tools/search-prospeo.ts": module_5
                })
            })
    })
});

export default moduleMap;
